### ISSUE TITLE
Serial Timeout

### ISSUE THREAD

**Issue by andygodber** [Strum355/currentcost-influx#1]
Hi Noah - thanks for your work on this.
Im getting "error reading from serial: Operation timed out"

Centos8 stream. Confirming device is /dev/ttyUSB0 and influx connection working (it created empty tables).
The CC device is able to be read by other simple serial loggers.

My first time with rust/cargo but managed to get deps installed.
Tried increase the timeout value to 30s but still no joy.

**Comment by Strum355** [comment]
Hi Andy,

Would you be able to share a screenshot of a working example of the CC device being read successfully by other serial readers? Specifically what serial readers you used, what serial settings they were configured for (or what defaults they use). 

And just to confirm, no data is being inserted into Influx and you've double checked the correct device path is set for this program?

Thanks!

**Comment by andygodber** [comment]
I went simple to start with and used minicom
minicom -D /dev/ttyUSB0 -b 57600


![image](https://user-images.githubusercontent.com/1061812/122686969-e138c780-d20b-11eb-8098-51f2e32d0d55.png)

and then a simple Python logger:
![image](https://user-images.githubusercontent.com/1061812/122687051-54423e00-d20c-11eb-8ea2-215f63633b43.png)

![image](https://user-images.githubusercontent.com/1061812/122687080-7a67de00-d20c-11eb-820c-13b361553913.png)

**Comment by Strum355** [comment]
Are you running minicom or reading from the serial port concurrently while using my program? Im asking this because, if memory serves me correctly, data from a serial port isnt sent to all listening/reading programs, so if youre reading with minicom and/or any particular logger while also using my program, this may explain the behavior.

**Comment by andygodber** [comment]
Confirming nothing else using ther serial/USB port.
However, Ive browsed the influxdb directly, and there is data in there, which is great news - it only seems to be about 10 rows though.
I'll start as a service as per the rest of the instructions and see how much is generated overnight.

**Comment by andygodber** [comment]
Ok - I suspect there was some process accessing the USB device, as you suggested, although I couldnt find it, and despite the other loggers working! (might be a rust requirement for single use?).
After a reboot, this issue has gone away. And the influxdb is being populated correctly.
However, raising a new one ;)

**Comment by andygodber** [comment]
haha - I spoke too soon - despite it seemingly working for a while the serial issue is back; suspect some system process is kicking in (any idea how to check?).
But its not urgent - Im getting the data I need.

**Comment by Strum355** [comment]
does `lsof | grep /dev/ttyUSB0` return anything?

**Comment by andygodber** [comment]
The only thing that is showing is currentcost, which is correct.
This issue comes and goes, so I suspect really is down to my environment and will close, but confirming new unrelated issue now also raised.
